<?php
/* Template Name: Nexora Studio */
?>
<?php get_header(); ?>
<section class="page-hero shell"><span class="eyebrow">01 / <?php echo esc_html(nexora_t('nav_studio')); ?></span><h1><?php echo esc_html(nexora_t('studio_title')); ?></h1><p><?php echo esc_html(nexora_t('studio_story')); ?></p></section>
<section class="studio-image-pair shell-wide"><figure class="reveal"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/brand/studio-01.webp'); ?>" alt="<?php echo esc_attr(nexora_b('میز بررسی ماکت و متریال در استودیوی نکسورا','Model and material review table at Nexora studio')); ?>" loading="lazy"></figure><figure class="reveal"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/brand/studio-02.webp'); ?>" alt="<?php echo esc_attr(nexora_b('فضای کار تیم طراحی نکسورا','Nexora design team workspace')); ?>" loading="lazy"></figure></section>
<section class="case-section shell"><div><span class="eyebrow">02 / <?php echo esc_html(nexora_t('philosophy')); ?></span></div><div class="case-copy"><p class="lead"><?php echo esc_html(nexora_b('به‌جای دنبال‌کردن یک امضای بصری ثابت، تلاش می‌کنیم هر پروژه از زمینه، اقلیم، بودجه و شیوه زندگی خودش شکل بگیرد. وجه مشترک پروژه‌ها باید دقت باشد، نه شباهت.','Instead of forcing a fixed visual signature, we let each project emerge from its context, climate, budget and patterns of use. The common thread should be precision, not similarity.')); ?></p></div></section>
<section class="process-section section shell"><span class="eyebrow">03 / <?php echo esc_html(nexora_t('process')); ?></span><div class="process-grid"><?php $steps=nexora_lang()==='fa'?[['01','شناخت','سایت، نیازها، بودجه و محدودیت‌ها را پیش از طراحی دقیق می‌کنیم.'],['02','جهت‌گیری','سناریوها را مقایسه و یک مسیر روشن برای پروژه انتخاب می‌کنیم.'],['03','توسعه','فضا، سازه، نور، مصالح و جزئیات هم‌زمان پیش می‌روند.'],['04','ساخت','در مرحله اجرا حضور داریم تا تصمیم‌های طراحی به واقعیت نزدیک بمانند.']]:[['01','Understand','We clarify site, needs, budget and constraints before drawing conclusions.'],['02','Direction','We compare scenarios and establish one clear path for the project.'],['03','Develop','Space, structure, light, material and detail evolve together.'],['04','Build','We remain involved during construction so design decisions survive contact with reality.']];foreach($steps as $s):?><article class="process-card reveal"><span><?php echo esc_html($s[0]); ?></span><h3><?php echo esc_html($s[1]); ?></h3><p><?php echo esc_html($s[2]); ?></p></article><?php endforeach;?></div></section>
<section class="section shell"><div class="section-heading"><div><span class="eyebrow">04 / <?php echo esc_html(nexora_t('team')); ?></span><h2><?php echo esc_html(nexora_b('یک تیم کوچک با مسئولیت مستقیم.','A compact team with direct responsibility.')); ?></h2></div></div><div class="team-grid"><?php $q=new WP_Query(['post_type'=>'nexora_team','posts_per_page'=>8,'orderby'=>'menu_order','order'=>'ASC','suppress_filters'=>false]);while($q->have_posts()):$q->the_post();?><article class="team-card reveal"><div class="team-avatar"><?php if(has_post_thumbnail()):the_post_thumbnail('medium',['loading'=>'lazy','alt'=>nexora_image_alt('hero')]);else:?><span><?php echo esc_html(nexora_substr(get_the_title(),0,1)); ?></span><?php endif;?></div><h3><?php the_title(); ?></h3><p><?php echo esc_html(wp_strip_all_tags(get_the_content())); ?></p></article><?php endwhile;wp_reset_postdata();?></div></section>
<section class="section shell recognition"><span class="eyebrow">05 / <?php echo esc_html(nexora_t('recognition')); ?></span><div class="recognition-grid"><div><strong>2018</strong><p><?php echo esc_html(nexora_b('تقدیر فرضی «Material Quiet»','Fictional “Material Quiet” citation')); ?></p></div><div><strong>2021</strong><p><?php echo esc_html(nexora_b('منتخب فرضی «Adaptive Rooms»','Fictional “Adaptive Rooms” selection')); ?></p></div><div><strong>2024</strong><p><?php echo esc_html(nexora_b('برگزیده فرضی «Second Life»','Fictional “Second Life” selection')); ?></p></div><div><strong>2025</strong><p><?php echo esc_html(nexora_b('سه پروژه در فهرست فرضی «Form & Field»','Three projects in fictional “Form & Field” selection')); ?></p></div></div><p class="demo-disclaimer"><?php echo esc_html(nexora_b('تمام نام پروژه‌ها، مشتریان و افتخارات این وب‌سایت برای نمونه‌کار فرضی ساخته شده‌اند.','All projects, clients and recognitions on this site are fictional and created for this portfolio demo.')); ?></p></section>
<?php get_footer(); ?>
