<?php
/* Template Name: Nexora Contact */
?>
<?php get_header();$b=nexora_brand();?>
<section class="page-hero shell"><span class="eyebrow">01 / <?php echo esc_html(nexora_t('nav_contact')); ?></span><h1><?php echo esc_html(nexora_t('contact_title')); ?></h1><p><?php echo esc_html(nexora_t('contact_intro')); ?></p></section>
<section class="contact-layout shell"><div class="contact-aside reveal"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/brand/contact.webp'); ?>" alt="<?php echo esc_attr(nexora_b('فضای ملاقات استودیوی نکسورا','Nexora studio meeting space')); ?>" loading="lazy"><div class="contact-facts"><div><span class="eyebrow"><?php echo esc_html(nexora_t('office')); ?></span><p><?php echo esc_html(nexora_b($b['address_fa'],$b['address_en'])); ?></p><a href="mailto:<?php echo esc_attr($b['email']); ?>"><?php echo esc_html($b['email']); ?></a><a href="tel:<?php echo esc_attr(preg_replace('/\s+/','',$b['phone'])); ?>"><?php echo esc_html($b['phone']); ?></a></div><div><span class="eyebrow"><?php echo esc_html(nexora_t('hours')); ?></span><p><?php echo esc_html(nexora_b($b['hours_fa'],$b['hours_en'])); ?></p></div></div></div><div class="contact-form-wrap reveal"><?php echo shortcode_exists('nexora_contact_form') ? do_shortcode('[nexora_contact_form]') : '<p class="nexora-form-status error">'.esc_html(nexora_b('برای فعال‌شدن فرم، افزونه Nexora Core را فعال کنید.','Activate Nexora Core to enable this form.')).'</p>'; ?></div></section>
<section class="contact-map shell-wide reveal" aria-label="<?php echo esc_attr(nexora_b('موقعیت دفتر فرضی نکسورا در تهران','Fictional Nexora studio location in Tehran')); ?>"><div class="map-grid" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="map-marker"><span></span><strong><?php echo esc_html($b['studio_name']); ?> / <?php echo esc_html(nexora_b('تهران','TEHRAN')); ?></strong><small><?php echo esc_html(nexora_b($b['address_fa'],$b['address_en'])); ?></small><?php if ( ! empty( $b['directions_url'] ) ) : ?><a class="text-link" target="_blank" rel="noopener noreferrer" href="<?php echo esc_url( $b['directions_url'] ); ?>"><?php echo esc_html( nexora_t( 'directions' ) ); ?> ↗</a><?php endif; ?></div></section>
<section class="section shell"><div class="section-heading"><div><span class="eyebrow">02 / <?php echo esc_html(nexora_t('faq')); ?></span></div></div><div class="faq-grid"><?php $faqs=nexora_lang()==='fa'?[['برای شروع پروژه چه اطلاعاتی لازم است؟','موقعیت، نوع فضا، متراژ تقریبی، زمان موردنظر و محدوده بودجه برای جلسه اول کافی است.'],['آیا پروژه خارج از تهران می‌پذیرید؟','بله. بسته به مرحله پروژه، جلسات آنلاین و بازدیدهای برنامه‌ریزی‌شده ترکیب می‌شوند.'],['هزینه طراحی چگونه مشخص می‌شود؟','پس از جلسه اولیه و مشخص‌شدن دامنه خدمات، پیشنهاد مالی مرحله‌بندی‌شده ارائه می‌شود.'],['آیا فقط طراحی داخلی هم انجام می‌دهید؟','بله؛ خدمات می‌تواند مستقل یا بخشی از پروژه کامل معماری باشد.']]:[['What do you need to start?','Location, project type, approximate area, desired timeline and a rough budget range are enough for the first meeting.'],['Do you work outside Tehran?','Yes. Depending on the stage, remote coordination is combined with planned site visits.'],['How are design fees defined?','After the first meeting and a clear scope, we issue a phased fee proposal.'],['Can we hire you only for interiors?','Yes. Services can be commissioned independently or as part of a complete architecture project.']];foreach($faqs as $f):?><details class="faq-item"><summary><?php echo esc_html($f[0]); ?></summary><p><?php echo esc_html($f[1]); ?></p></details><?php endforeach;?></div></section>
<?php get_footer(); ?>
