<?php
get_header();
$id = get_the_ID();
$terms = get_the_terms( $id, 'nexora_project_type' );
$slugs = $terms && ! is_wp_error( $terms ) ? wp_list_pluck( $terms, 'slug' ) : [];
$gallery = nexora_gallery_ids( $id );
$next = nexora_next_project( $id );
$section = 2;
?>
<article class="project-case">
<section class="project-hero shell"><span class="eyebrow">01 / <?php echo esc_html( $slugs ? implode( ' / ', array_map( 'nexora_project_type_label', $slugs ) ) : nexora_t( 'nav_projects' ) ); ?></span><h1><?php the_title(); ?></h1><p class="project-intro"><?php echo esc_html( get_the_excerpt() ); ?></p><div class="project-meta"><?php foreach ( [ 'location' => '_nexora_location', 'area' => '_nexora_area', 'year' => '_nexora_year', 'client' => '_nexora_client', 'architect' => '_nexora_architect', 'status' => '_nexora_status', 'duration' => '_nexora_duration', 'budget' => '_nexora_budget' ] as $label => $key ) : $value = nexora_meta( $key ); if ( $value ) : ?><div><span><?php echo esc_html( nexora_t( $label ) ); ?></span><strong><?php echo esc_html( $value ); ?></strong></div><?php endif; endforeach; ?></div></section>
<section class="project-feature shell-wide reveal"><?php if ( has_post_thumbnail() ) { the_post_thumbnail( 'full', [ 'fetchpriority' => 'high', 'alt' => nexora_image_alt( 'hero' ) ] ); } ?></section>
<?php foreach ( [ [ 'context', '_nexora_context' ], [ 'brief', '_nexora_brief' ], [ 'concept', '_nexora_concept' ] ] as [ $label, $key ] ) : $value = nexora_meta( $key ); if ( ! $value ) { continue; } ?>
<section class="case-section shell"><div class="case-label"><span class="eyebrow"><?php echo esc_html( str_pad( (string) $section, 2, '0', STR_PAD_LEFT ) ); ?> / <?php echo esc_html( nexora_t( $label ) ); ?></span></div><div class="case-copy"><p class="lead"><?php echo esc_html( $value ); ?></p><?php if ( 'concept' === $label ) : ?><div class="prose"><?php the_content(); ?></div><?php endif; ?></div><?php if ( 'concept' === $label ) { nexora_share_links(); } ?></section>
<?php ++$section; endforeach; ?>
<?php $before = (int) nexora_meta( '_nexora_before_id' ); $after = (int) nexora_meta( '_nexora_after_id' ); if ( $before && $after ) : ?>
<section class="before-after-section shell"><div class="section-heading"><div><span class="eyebrow"><?php echo esc_html( str_pad( (string) $section, 2, '0', STR_PAD_LEFT ) ); ?> / <?php echo esc_html( nexora_t( 'before_after' ) ); ?></span><h2><?php echo esc_html( nexora_b( 'تغییر، بدون پاک‌کردن حافظه فضا.', 'Transformation without erasing the memory of place.' ) ); ?></h2></div></div><div class="before-after" data-before-after><div class="after-image"><?php echo wp_get_attachment_image( $after, 'full', false, [ 'loading' => 'lazy', 'alt' => nexora_image_alt( 'after' ) ] ); ?></div><div class="before-image" data-before-layer><?php echo wp_get_attachment_image( $before, 'full', false, [ 'loading' => 'lazy', 'alt' => nexora_image_alt( 'before' ) ] ); ?></div><input type="range" min="0" max="100" value="50" aria-label="<?php echo esc_attr( nexora_t( 'compare' ) ); ?>" data-before-range><span class="ba-handle" data-before-handle aria-hidden="true"></span><span class="ba-label ba-before"><?php echo esc_html( nexora_t( 'before' ) ); ?></span><span class="ba-label ba-after"><?php echo esc_html( nexora_t( 'after' ) ); ?></span></div></section>
<?php ++$section; endif; ?>
<?php if ( $gallery ) : ?><section class="case-gallery shell-wide"><div class="section-heading shell"><div><span class="eyebrow"><?php echo esc_html( str_pad( (string) $section, 2, '0', STR_PAD_LEFT ) ); ?> / <?php echo esc_html( nexora_t( 'gallery' ) ); ?></span></div></div><div class="masonry-gallery"><?php foreach ( $gallery as $i => $gallery_id ) : ?><figure class="reveal gallery-<?php echo (int) $i; ?>"><?php echo wp_get_attachment_image( $gallery_id, 'full', false, [ 'loading' => 'lazy', 'alt' => nexora_image_alt( 'gallery', $i + 1 ) ] ); ?></figure><?php endforeach; ?></div></section><?php ++$section; endif; ?>
<?php $pairs = [ [ 'challenge', '_nexora_challenge' ], [ 'solution', '_nexora_solution' ], [ 'environment', '_nexora_environment' ], [ 'lighting', '_nexora_lighting' ] ]; for ( $i = 0; $i < count( $pairs ); $i += 2 ) : ?>
<section class="case-section split shell"><?php foreach ( array_slice( $pairs, $i, 2 ) as [ $label, $key ] ) : $value = nexora_meta( $key ); if ( ! $value ) { continue; } ?><div><span class="eyebrow"><?php echo esc_html( str_pad( (string) $section, 2, '0', STR_PAD_LEFT ) ); ?> / <?php echo esc_html( nexora_t( $label ) ); ?></span><p><?php echo esc_html( $value ); ?></p></div><?php ++$section; endforeach; ?></section>
<?php endfor; ?>
<section class="case-details shell"><?php foreach ( [ 'materials' => '_nexora_materials', 'timeline' => '_nexora_timeline', 'awards' => '_nexora_awards', 'credits' => '_nexora_credits' ] as $label => $key ) : $value = nexora_meta( $key ); if ( ! $value ) { continue; } ?><div class="detail-card reveal"><span class="eyebrow"><?php echo esc_html( nexora_t( $label ) ); ?></span><p><?php echo esc_html( $value ); ?></p></div><?php endforeach; ?></section>
<?php $plan = (int) nexora_meta( '_nexora_plan_id' ); if ( $plan ) : ?><section class="plan-section shell"><div class="section-heading"><div><span class="eyebrow"><?php echo esc_html( str_pad( (string) $section, 2, '0', STR_PAD_LEFT ) ); ?> / <?php echo esc_html( nexora_t( 'plan' ) ); ?></span></div></div><div class="plan-image reveal"><?php echo wp_get_attachment_image( $plan, 'full', false, [ 'loading' => 'lazy', 'alt' => nexora_image_alt( 'plan' ) ] ); ?></div></section><?php ++$section; endif; ?>
<?php if ( $next ) : ?><section class="next-project shell-wide reveal"><a href="<?php echo esc_url( get_permalink( $next ) ); ?>"><span class="eyebrow"><?php echo esc_html( nexora_t( 'next_project' ) ); ?></span><h2><?php echo esc_html( get_the_title( $next ) ); ?></h2><?php echo get_the_post_thumbnail( $next, 'full', [ 'loading' => 'lazy', 'alt' => nexora_image_alt( 'hero', 0, $next->ID ) ] ); ?><span class="next-arrow" aria-hidden="true">↗</span></a></section><?php endif; ?>
</article>
<?php get_footer(); ?>
